//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Translator.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Translator.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __f__AnonymousType0$2 = function() {
        ///};
        ///
        ///__f__AnonymousType0$2.prototype.$ctor = function(/*_Key_j__TPar*/ Key, /*_Value_j__TPar*/ Value) {
        ///	this._Key_i__Field = Key;
        ///	this._Value_i__Field = Value;
        ///	return this;
        ///};
        ///
        ///__f__AnonymousType0$2.prototype.get_Key = function() {
        ///	return this._Key_i__Field;
        ///};
        ///
        ///__f__AnonymousType0$2.prototype.get_Value = function() {
        ///	return this._Value_i__Field;
        ///};
        ///
        ///$Namespace(&apos;System&apos;);
        ///
        ///System.Console = function() {
        ///};
        ///
        ///System.Console.WriteLine = function(/*S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnonymousType {
            get {
                return ResourceManager.GetString("AnonymousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;System&apos;);
        ///
        ///System.Exception = function() {
        ///};
        ///
        ///System.Exception.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///System.SystemException = function() {
        ///	this.$super.constructor();
        ///};
        ///System.SystemException.$extend(System.Exception);
        ///
        ///System.SystemException.prototype.$ctor = function() {
        ///	this.$super.$ctor.call(this);
        ///	return this;
        ///};
        ///
        ///System.NotImplementedException = function() {
        ///	this.$super.constructor();
        ///};
        ///System.NotImplementedException.$extend(System.SystemException);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Callback {
            get {
                return ResourceManager.GetString("Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.Base = function() {
        ///};
        ///
        ///H8.Derived = function() {
        ///	this.$super.constructor();
        ///};
        ///H8.Derived.$extend(H8.Base);
        ///
        ///H8.Derived.NextId = function() {
        ///	H8.Derived.counter = H8.Derived.counter + 1;
        ///	return H8.Derived.counter;
        ///};
        ///
        ///H8.Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.Derived.prototype.$ctor = function() {
        ///	this.id = H8.Derived.NextId();
        ///	this.$super.$ctor.call(this);
        ///	return this;
        ///};
        ///
        ///H8.Base.prototype.BaseMethod = function() {
        ///};
        ///
        ///H8.Derived.p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallDerived {
            get {
                return ResourceManager.GetString("CallDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;System&apos;);
        ///
        ///System.Console = function() {
        ///};
        ///
        ///System.Console.WriteLine = function(/*System.String*/ value) {
        ///	console.log(value);
        ///};
        ///
        ///System.Math = function() {
        ///};
        ///
        ///System.Math.Sin = function(/*System.Double*/ a) {
        ///	return Math.sin(a);
        ///};
        ///
        ///System.Math.Cos = function(/*System.Double*/ a) {
        ///	return Math.cos(a);
        ///};
        ///
        ///$Namespace(&apos;H8&apos;);
        ///
        ///H8.SourceTests = function() {
        ///};
        ///
        ///H8.SourceTests.prototype.TakeParameters = function(/*System.String*/ str, /*System.Int32*/ value, /*System.D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallTakeParameters {
            get {
                return ResourceManager.GetString("CallTakeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.Cifuentes = function() {
        ///	var x = 5;
        ///	var y = x * 5;
        ///	if (x &lt; y) {
        ///		x = x * y;
        ///		if ((x * 2) &lt;= y) {
        ///			y = y &lt;&lt; 3;
        ///		}
        ///		else {
        ///			x = x &lt;&lt; 3;
        ///		}
        ///	}
        ///	var a = 0;
        ///	while(a &lt; 10) {
        ///		var b = a;
        ///		do {
        ///			b = b + 1;
        ///			System.Console.WriteLine(&quot;{0}, {1}&quot;, a, b);
        ///		} while(b &lt; 5);
        ///		a = a + 1;
        ///	}
        ///	if ((x &lt; y) || ((y * 2) &gt; x)) {
        ///		x = (x + y) - 10;
        ///		y = y / 2;
        ///	}
        ///};
        ///.
        /// </summary>
        internal static string Cifuentes {
            get {
                return ResourceManager.GetString("Cifuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SourceTests_InnerClassTest = function() {
        ///};
        ///
        ///H8.SourceTests_InnerClassTest.prototype.set_Text = function(/*System.String*/ value) {
        ///	this._Text_k__BackingField = value;
        ///};
        ///
        ///H8.SourceTests_InnerClassTest.prototype.set_Value = function(/*System.Int32*/ value) {
        ///	this._Value_k__BackingField = value;
        ///};
        ///
        ///H8.SourceTests_InnerClassTest.prototype.$ctor = function(/*System.String*/ text, /*System.Int32*/ value) {
        ///	this.set_Text(text);
        ///	this.set_Value(value);
        ///	return this;
        ///};        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateInnerObject {
            get {
                return ResourceManager.GetString("CreateInnerObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.OuterClassTest = function() {
        ///};
        ///
        ///H8.OuterClassTest.prototype.set_Text = function(/*System.String*/ value) {
        ///	this._Text_k__BackingField = value;
        ///};
        ///
        ///H8.OuterClassTest.prototype.set_Value = function(/*System.Int32*/ value) {
        ///	this.m_value = value;
        ///};
        ///
        ///H8.OuterClassTest.prototype.$ctor = function(/*System.String*/ text, /*System.Int32*/ value) {
        ///	this.set_Text(text);
        ///	this.set_Value(value);
        ///	return this;
        ///};
        ///
        ///H8.OuterClassTest.prototype.$ctor = function() {
        ///	return th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateOuterObject {
            get {
                return ResourceManager.GetString("CreateOuterObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2009, Frank Laub
        /////
        ///// This file is part of DotWeb.
        /////
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        /////
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecorationTest {
            get {
                return ResourceManager.GetString("DecorationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.DecorationTests = function() {
        ///};
        ///
        ///H8.DecorationTests.prototype.box_OnMouseOver = function(/*DotWeb.Client.Dom.Events.MouseEvent*/ evt) {
        ///};
        ///
        ///H8.DecorationTests.prototype.TestCastInterface = function() {
        ///	var element = $doc.getElementById(&quot;box&quot;);
        ///	var box = /*(DotWeb.Client.Dom.Html.HtmlDivElement)*/element;
        ///	box.onmouseover = $Delegate(this, this.box_OnMouseOver);
        ///};
        ///.
        /// </summary>
        internal static string DecorationTest_CastInterface {
            get {
                return ResourceManager.GetString("DecorationTest_CastInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;System&apos;);
        ///
        ///System.Console = function() {
        ///};
        ///
        ///System.Console.WriteLine = function(/*System.Object*/ value) {
        ///	console.log(value);
        ///};
        ///
        ///$Namespace(&apos;H8&apos;);
        ///
        ///H8.DecorationTests = function() {
        ///};
        ///
        ///H8.DecorationTests.prototype.TestJsAnonymous = function() {
        ///	var __g__initLocal0 = {};
        ///	__g__initLocal0.X = 1;
        ///	__g__initLocal0.y = 2;
        ///	var item = __g__initLocal0;
        ///	item.X = item.y;
        ///	item.y = item.X;
        ///	var CS$0$0000 = new /*H8.AnonymousClass*/Array(2);
        ///	var __g__initLocal1 = {};
        ///	__g__in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecorationTest_JsAnonymous {
            get {
                return ResourceManager.GetString("DecorationTest_JsAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.DecorationTests.prototype.TestJsArray = function() {
        ///	var array = new Array();
        ///	if (Array.isArray(array)) {
        ///		var part = array.slice(0, 1);
        ///		System.Console.WriteLine(part.join(&quot;,&quot;));
        ///	}
        ///	array.splice(0, 0);
        ///	array.splice(0, 0, 1);
        ///	array.splice(0, 0, 1, &quot;two&quot;);
        ///	var x = new Array(1, 2);
        ///	System.Console.WriteLine(x[0]);
        ///	x[1] = 1;
        ///};
        ///.
        /// </summary>
        internal static string DecorationTest_JsArray {
            get {
                return ResourceManager.GetString("DecorationTest_JsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.DecorationTests.prototype.TestJsCamelCase = function() {
        ///	var x = new H8.CamelCaseTest().$ctor();
        ///	x.foo();
        ///	this.camelCase();
        ///};
        ///.
        /// </summary>
        internal static string DecorationTest_JsCamelCase {
            get {
                return ResourceManager.GetString("DecorationTest_JsCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.DecorationTests.prototype.TestJsCode = function(/*System.String*/ arg) {
        ///	alert(arg);
        ///};
        ///.
        /// </summary>
        internal static string DecorationTest_JsCode {
            get {
                return ResourceManager.GetString("DecorationTest_JsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.IntrinsicClass = function() {
        ///};
        ///
        ///H8.IntrinsicClass.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///$Namespace(&apos;System&apos;);
        ///
        ///System.Console = function() {
        ///};
        ///
        ///System.Console.Write = function(/*System.Int32*/ value) {
        ///	console.log(value);
        ///};
        ///
        ///H8.DecorationTests = function() {
        ///};
        ///
        ///H8.DecorationTests.prototype.TestJsIntrinsic = function() {
        ///	var __g__initLocal3 = new H8.IntrinsicClass().$ctor();
        ///	__g__initLocal3.Value = 1;
        ///	var item = __g__initLocal3;
        ///	System.Conso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecorationTest_JsIntrinsic {
            get {
                return ResourceManager.GetString("DecorationTest_JsIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.DecorationTests.prototype.TestJsMacro = function() {
        ///	this.jQuery(&quot;*&quot;);
        ///	H8.DecorationTests.jQuery(&quot;*&quot;);
        ///	H8.DecorationTests.TakeJQuery(this.jQuery(&quot;#id&quot;));
        ///	System.Console.WriteLine($doc.getElementById(&quot;id&quot;));
        ///};
        ///.
        /// </summary>
        internal static string DecorationTest_JsMacro {
            get {
                return ResourceManager.GetString("DecorationTest_JsMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultNamespaceTest = function() {
        ///};
        ///
        ///DefaultNamespaceTest.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///DefaultNamespaceTest.prototype.set_Value = function(/*System.Int32*/ value) {
        ///	this._Value_k__BackingField = value;
        ///};
        ///
        ///$Namespace(&apos;Foo&apos;);
        ///
        ///Foo.FooNamespaceTest = function() {
        ///};
        ///
        ///Foo.FooNamespaceTest.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///DefaultNamespaceTest.prototype.get_Value = function() {
        ///	return this._Value_k__BackingField;
        ///};
        ///
        ///Foo.FooNamespaceTest.prototype. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecorationTest_JsNamespace {
            get {
                return ResourceManager.GetString("DecorationTest_JsNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.EnumArray = function() {
        ///	System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(new /*System.Int32*/Array(4), [ 1, 2, 3, 4 ]);
        ///	var array = new /*System.Int32*/Array(4);
        ///	var CS$6$0000 = array;
        ///	var CS$7$0001 = 0;
        ///	while(CS$7$0001 &lt; /*(System.Int32)*/CS$6$0000.length) {
        ///		var item = CS$6$0000[CS$7$0001];
        ///		System.Console.WriteLine(item);
        ///		CS$7$0001 = CS$7$0001 + 1;
        ///	}
        ///};
        ///.
        /// </summary>
        internal static string EnumArray {
            get {
                return ResourceManager.GetString("EnumArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.GitHub_Issue3 = function() {
        ///	new jQueryTest($doc);
        ///};
        ///.
        /// </summary>
        internal static string GitHub_Issue3 {
            get {
                return ResourceManager.GetString("GitHub_Issue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SourceTests = function() {
        ///};
        ///
        ///H8.SourceTests._GitHub_Issue4_b__2 = function() {
        ///	$wnd.alert(&quot;test&quot;);
        ///};
        ///
        ///H8.SourceTests.prototype.GitHub_Issue4 = function() {
        ///	if (!H8.SourceTests.CS$__9__CachedAnonymousMethodDelegate3) {
        ///		H8.SourceTests.CS$__9__CachedAnonymousMethodDelegate3 = $Delegate(H8.SourceTests, H8.SourceTests._GitHub_Issue4_b__2);
        ///	}
        ///	var action = H8.SourceTests.CS$__9__CachedAnonymousMethodDelegate3;
        ///	action();
        ///};
        ///.
        /// </summary>
        internal static string GitHub_Issue4 {
            get {
                return ResourceManager.GetString("GitHub_Issue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;GitHub_Issue5&apos;);
        ///
        ///GitHub_Issue5.Class1 = function() {
        ///};
        ///
        ///GitHub_Issue5.Class1._.ctor_b__0 = function() {
        ///	$wnd.alert(&quot;test&quot;);
        ///};
        ///
        ///GitHub_Issue5.Class1.prototype.Call = function(/*System.Action*/ action) {
        ///	action();
        ///};
        ///
        ///GitHub_Issue5.Class1.prototype.$ctor = function() {
        ///	var R_1 = this;
        ///	if (!GitHub_Issue5.Class1.CS$__9__CachedAnonymousMethodDelegate1) {
        ///		GitHub_Issue5.Class1.CS$__9__CachedAnonymousMethodDelegate1 = $Delegate(GitHub_Issue5.Class1, GitHub_Issue5.Class1._.ctor_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitHub_Issue5 {
            get {
                return ResourceManager.GetString("GitHub_Issue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;GitHub_Issue5&apos;);
        ///
        ///GitHub_Issue5.Class1 = function() {
        ///};
        ///
        ///GitHub_Issue5.Class1._.ctor_b__0 = function() {
        ///	$wnd.alert(&quot;test&quot;);
        ///};
        ///
        ///GitHub_Issue5.Class1.prototype.Call = function(/*System.Action*/ action) {
        ///	action();
        ///};
        ///
        ///GitHub_Issue5.Class1.prototype.$ctor = function() {
        ///	var R_1 = this;
        ///	if (!GitHub_Issue5.Class1.CS$__9__CachedAnonymousMethodDelegate1) {
        ///		GitHub_Issue5.Class1.CS$__9__CachedAnonymousMethodDelegate1 = $Delegate(GitHub_Issue5.Class1, GitHub_Issue5.Class1._.ctor_b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitHub_Issue6 {
            get {
                return ResourceManager.GetString("GitHub_Issue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.HelloWorld = function() {
        ///	System.Console.WriteLine(&quot;Hello World!&quot;);
        ///};
        ///
        ///.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.IndexerTest = function() {
        ///};
        ///
        ///H8.IndexerTest.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///$Namespace(&apos;System&apos;);
        ///
        ///System.Console = function() {
        ///};
        ///
        ///System.Console.WriteLine = function(/*System.Object*/ value) {
        ///	console.log(value);
        ///};
        ///
        ///H8.SourceTests = function() {
        ///};
        ///
        ///H8.SourceTests.prototype.Indexer = function() {
        ///	var indexer = new H8.IndexerTest().$ctor();
        ///	indexer[&quot;Test&quot;] = 1;
        ///	var value = indexer[&quot;Test&quot;];
        ///	System.Console.WriteLine(value);
        ///};
        ///.
        /// </summary>
        internal static string Indexer {
            get {
                return ResourceManager.GetString("Indexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SourceTests = function() {
        ///};
        ///
        ///H8.SourceTests._Linq_b__2 = function(ch /*System.Char*/) {
        ///	return System.Char.IsDigit(ch);
        ///};
        ///
        ///H8.SourceTests.prototype.Linq = function() {
        ///	var loc0 = &quot;ABCDE99F-J74-12-89A&quot;;
        ///	if (!H8.SourceTests.CS$__9__CachedAnonymousMethodDelegate3) {
        ///		H8.SourceTests.CS$__9__CachedAnonymousMethodDelegate3 = $Delegate(H8.SourceTests, H8.SourceTests._Linq_b__2);
        ///	}
        ///	var loc1 = System.Linq.Enumerable.Where(loc0, H8.SourceTests.CS$__9__CachedAnonymousMethod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Linq {
            get {
                return ResourceManager.GetString("Linq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2009, Frank Laub
        /////
        ///// This file is part of DotWeb.
        /////
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        /////
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NativeTest {
            get {
                return ResourceManager.GetString("NativeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.NativeTest.prototype.TestTuple = function() {
        ///	var __g__initLocal0 = {};
        ///	__g__initLocal0.id = 666;
        ///	__g__initLocal0.value = &quot;value&quot;;
        ///	var config = __g__initLocal0;
        ///	var tuple = new Tuple(config);
        ///	var id = tuple.id;
        ///	System.Console.WriteLine(id);
        ///	tuple.id = 9;
        ///};
        ///.
        /// </summary>
        internal static string NativeTest_TestTuple {
            get {
                return ResourceManager.GetString("NativeTest_TestTuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.SwitchInsideWhile = function(/*System.Int32*/ x) {
        ///	System.Console.WriteLine(&quot;enter&quot;);
        ///	while(x &gt; 10) {
        ///		System.Console.WriteLine(&quot;head&quot;);
        ///		var CS$0$0000 = x;
        ///		switch(CS$0$0000) {
        ///			case 0:
        ///				System.Console.WriteLine(&quot;Zero: return&quot;);
        ///				return;
        ///			case 1:
        ///			case 2:
        ///				System.Console.WriteLine(&quot;One &amp; Two&quot;);
        ///				break;
        ///			case 3:
        ///				System.Console.WriteLine(&quot;Three: continue&quot;);
        ///				continue;
        ///			default:
        ///				System.Console.WriteLine(&quot;default&quot;);
        ///				break;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SwitchInsideWhile {
            get {
                return ResourceManager.GetString("SwitchInsideWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2009, Frank Laub
        /////
        ///// This file is part of DotWeb.
        /////
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        /////
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest {
            get {
                return ResourceManager.GetString("SystemTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SystemTests_Base = function() {
        ///};
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived = function() {
        ///	this.$super.constructor();
        ///};
        ///H8.SystemTests_Derived.$extend(H8.SystemTests_Base);
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo();
        ///};
        ///
        ///H8.SystemTests = function() {
        ///};
        ///
        ///H8.SystemTests.prototype.TestBase = function() {
        ///	var x = ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest_TestBase {
            get {
                return ResourceManager.GetString("SystemTest_TestBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SystemTests_Base = function() {
        ///};
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Derived = function() {
        ///	this.$super.constructor();
        ///};
        ///H8.SystemTests_Derived.$extend(H8.SystemTests_Base);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor.call(this);
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest_TestDerived {
            get {
                return ResourceManager.GetString("SystemTest_TestDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SystemTests_Base = function() {
        ///};
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Derived = function() {
        ///	this.$super.constructor();
        ///};
        ///H8.SystemTests_Derived.$extend(H8.SystemTests_Base);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor.call(this);
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest_TestDerivedThruBase {
            get {
                return ResourceManager.GetString("SystemTest_TestDerivedThruBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.SystemTests_Base = function() {
        ///};
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Derived = function() {
        ///	this.$super.constructor();
        ///};
        ///H8.SystemTests_Derived.$extend(H8.SystemTests_Base);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor.call(this);
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest_TestDerivedThruBaseIndirect {
            get {
                return ResourceManager.GetString("SystemTest_TestDerivedThruBaseIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;System.Collections.Generic&apos;);
        ///
        ///System.Collections.Generic.List$1 = function() {
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.$ctor = function() {
        ///	this.items = new Array();
        ///	return this;
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.Add = function(/*T*/ item) {
        ///	this.items.push(item);
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.toString = function() {
        ///	var V_0 = &quot;[ &quot; + this.items.toString() + &quot; ]&quot;;
        ///	return V_0;
        ///};
        ///
        ///$Namespace(&apos;System&apos;);
        ///
        ///System.Console = function()  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTest_TestList {
            get {
                return ResourceManager.GetString("SystemTest_TestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SourceTests.prototype.TakeParameters = function(/*System.String*/ str, /*System.Int32*/ value, /*System.Double[]*/ rad) {
        ///	System.Console.WriteLine(str);
        ///	var x = System.Math.Sin(rad[value] * 1.570795);
        ///	return System.Math.Cos(x);
        ///};
        ///.
        /// </summary>
        internal static string TakeParameters {
            get {
                return ResourceManager.GetString("TakeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Namespace(&apos;H8&apos;);
        ///
        ///H8.Generic$1 = function() {
        ///};
        ///
        ///H8.Generic$1.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.Generic$1_Nested = function() {
        ///};
        ///
        ///H8.Generic$1_Nested.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.Generic$1_Nested_Inner = function() {
        ///};
        ///
        ///H8.Generic$1_Nested_Inner.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.Generic$1_Nested_Inner.prototype.Foo = function() {
        ///};
        ///
        ///H8.Generic$1_Nested.prototype.Foo = function() {
        ///	var x = new H8.Generic$1_Nested_Inn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestGenericNested {
            get {
                return ResourceManager.GetString("TestGenericNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2009, Frank Laub
        /////
        ///// This file is part of DotWeb.
        /////
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        /////
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTest {
            get {
                return ResourceManager.GetString("TranslationTest", resourceCulture);
            }
        }
    }
}
