H8.SystemTests.prototype.TestCastPrimitive = function(i, f, d) {
	this.TakeInt(i);
	this.TakeInt(Math.floor(f));
	this.TakeInt(Math.floor(d));
	this.TakeInt(i * i);
	this.TakeInt(Math.floor(i * f));
	this.TakeInt(Math.floor(i * d));
	this.TakeInt(Math.floor(f * f));
	this.TakeInt(Math.floor(f * d));
	this.TakeInt(Math.floor(d * d));
	this.TakeFloat(i);
	this.TakeFloat(f);
	this.TakeFloat(d);
	this.TakeFloat(i * i);
	this.TakeFloat(i * f);
	this.TakeFloat(i * d);
	this.TakeFloat(f * f);
	this.TakeFloat(f * d);
	this.TakeFloat(d * d);
	this.TakeDouble(i);
	this.TakeDouble(f);
	this.TakeDouble(d);
	this.TakeDouble(i * i);
	this.TakeDouble(i * f);
	this.TakeDouble(i * d);
	this.TakeDouble(f * f);
	this.TakeDouble(f * d);
	this.TakeDouble(d * d);
};
