// Generated by H8 at: 9/8/2009 9:41:48 AM

// Copyright 2009, Frank Laub
//
// This file is part of DotWeb.
//
// DotWeb is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// DotWeb is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with DotWeb.  If not, see <http://www.gnu.org/licenses/>.

$wnd = window;
$doc = $wnd.document;

Object.prototype.$extend = function(superclass) {
	var tmp = function() {};
	tmp.prototype = superclass.prototype;
	this.prototype = new tmp();
	this.prototype.constructor = this;
	this.prototype.$super = tmp.prototype;
};

$Delegate = function(scope, target) {
	return function() {
		return target.apply(scope, arguments);
	};
};

if(typeof(DotWeb) == 'undefined') DotWeb = {};

if(typeof(DotWeb.Client) == 'undefined') DotWeb.Client = {};

DotWeb.Client.JsScript = function() {
};

DotWeb.Client.JsScript.prototype.$ctor = function() {
	return this;
};

DotWeb.Client.JsScript.prototype.get_Window = function() {
	return $wnd;
};

if(typeof(DotWeb.Sample) == 'undefined') DotWeb.Sample = {};

if(typeof(DotWeb.Sample.Script) == 'undefined') DotWeb.Sample.Script = {};

if(typeof(DotWeb.Sample.Script.Test) == 'undefined') DotWeb.Sample.Script.Test = {};

DotWeb.Sample.Script.Test.EventHandler = function() {
	this.$super.constructor();
};
DotWeb.Sample.Script.Test.EventHandler.$extend(DotWeb.Client.JsScript);

DotWeb.Sample.Script.Test.EventHandler.prototype.box_OnMouseOver = function() {
	// nop
	this.box.style.backgroundColor = "red";
	// nop
};

DotWeb.Sample.Script.Test.EventHandler.prototype.box_OnMouseOut = function() {
	// nop
	this.box.style.backgroundColor = "black";
	// nop
};

DotWeb.Sample.Script.Test.EventHandler.prototype.$ctor = function() {
	this.$super.$ctor.call(this);
	// nop
	// nop
	this.box = this.get_Window().document.getElementById("box");
	this.box.onmouseover = $Delegate(this, this.box_OnMouseOver);
	// nop
	this.box.onmouseout = $Delegate(this, this.box_OnMouseOut);
	// nop
	// nop
	return this;
};

$wnd.onload = function() {
	new DotWeb.Sample.Script.Test.EventHandler().$ctor();
}
