// Generated by H8 at: 9/8/2009 9:45:30 AM

// Copyright 2009, Frank Laub
//
// This file is part of DotWeb.
//
// DotWeb is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// DotWeb is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with DotWeb.  If not, see <http://www.gnu.org/licenses/>.

$wnd = window;
$doc = $wnd.document;

Object.prototype.$extend = function(superclass) {
	var tmp = function() {};
	tmp.prototype = superclass.prototype;
	this.prototype = new tmp();
	this.prototype.constructor = this;
	this.prototype.$super = tmp.prototype;
};

$Delegate = function(scope, target) {
	return function() {
		return target.apply(scope, arguments);
	};
};

if(typeof(DotWeb) == 'undefined') DotWeb = {};

if(typeof(DotWeb.Client) == 'undefined') DotWeb.Client = {};

DotWeb.Client.JsScript = function() {
};

DotWeb.Client.JsScript.prototype.$ctor = function() {
	return this;
};

if(typeof(DotWeb.Sample) == 'undefined') DotWeb.Sample = {};

if(typeof(DotWeb.Sample.Script) == 'undefined') DotWeb.Sample.Script = {};

if(typeof(DotWeb.Sample.Script.Test) == 'undefined') DotWeb.Sample.Script.Test = {};

DotWeb.Sample.Script.Test.NativeCallback_Console = function() {
};

DotWeb.Sample.Script.Test.NativeCallback_Console.Write = function(obj /*System.Object*/) {
	console.log(obj);
};

DotWeb.Sample.Script.Test.NativeCallback = function() {
	this.$super.constructor();
};
DotWeb.Sample.Script.Test.NativeCallback.$extend(DotWeb.Client.JsScript);

DotWeb.Sample.Script.Test.NativeCallback.prototype.$ctor = function() {
	this.$super.$ctor.call(this);
	// nop
	// nop
	DotWeb.Sample.Script.Test.NativeCallback_Console.Write("Hi");
	// nop
	var loc0 = new NativeObject();
	DotWeb.Sample.Script.Test.NativeCallback_Console.Write(loc0);
	// nop
	var loc3 = {};
	loc3.nativeObject = loc0;
	// nop
	var loc1 = loc3;
	DotWeb.Sample.Script.Test.NativeCallback_Console.Write(loc1);
	// nop
	var loc2 = new NativeCaller(loc1);
	DotWeb.Sample.Script.Test.NativeCallback_Console.Write(loc2);
	// nop
	loc2.Start();
	// nop
	// nop
	return this;
};

$wnd.onload = function() {
	new DotWeb.Sample.Script.Test.NativeCallback().$ctor();
}
