// Generated by H8 at: 9/8/2009 9:45:11 AM

// Copyright 2009, Frank Laub
//
// This file is part of DotWeb.
//
// DotWeb is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// DotWeb is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with DotWeb.  If not, see <http://www.gnu.org/licenses/>.

$wnd = window;
$doc = $wnd.document;

Object.prototype.$extend = function(superclass) {
	var tmp = function() {};
	tmp.prototype = superclass.prototype;
	this.prototype = new tmp();
	this.prototype.constructor = this;
	this.prototype.$super = tmp.prototype;
};

$Delegate = function(scope, target) {
	return function() {
		return target.apply(scope, arguments);
	};
};

if(typeof(DotWeb) == 'undefined') DotWeb = {};

if(typeof(DotWeb.Client) == 'undefined') DotWeb.Client = {};

DotWeb.Client.JsScript = function() {
};

DotWeb.Client.JsScript.prototype.$ctor = function() {
	return this;
};

if(typeof(DotWeb.Sample) == 'undefined') DotWeb.Sample = {};

if(typeof(DotWeb.Sample.Script) == 'undefined') DotWeb.Sample.Script = {};

DotWeb.Sample.Script.SimpleScript = function() {
	this.$super.constructor();
};
DotWeb.Sample.Script.SimpleScript.$extend(DotWeb.Client.JsScript);

DotWeb.Sample.Script.SimpleScript.prototype.OnEvent = function(tuple /*Tuple*/, id /*System.Int32*/) {
	// nop
	console.log(tuple.Value);
	// nop
};

DotWeb.Client.JsScript.prototype.get_Window = function() {
	return $wnd;
};

DotWeb.Sample.Script.SimpleScript.prototype.OnEvent = function() {
	// nop
	console.log("OnEvent");
	// nop
};

DotWeb.Sample.Script.SimpleScript.prototype.$ctor = function() {
	this.$super.$ctor.call(this);
	// nop
	// nop
	var loc4 = {};
	loc4.id = 666;
	loc4.value = "value";
	var loc0 = loc4;
	var loc1 = new Tuple(loc0);
	var loc2 = loc1.id;
	console.log("id: ");
	// nop
	console.log(loc2);
	// nop
	loc1.id = 9;
	// nop
	loc1.handler = $Delegate(this, this.OnEvent);
	// nop
	console.log("before");
	// nop
	loc1.fireEvent();
	// nop
	Tuple.StaticMethod(2, 5);
	// nop
	var loc3 = Tuple.Factory();
	console.log(loc3.id);
	// nop
	this.get_Window().onblur = $Delegate(this, this.OnEvent);
	// nop
	// nop
	return this;
};

$wnd.onload = function() {
	new DotWeb.Sample.Script.SimpleScript().$ctor();
}
