// Generated by H8 at: 1/19/2009 8:36:38 AM
Object.prototype.$extend = function(superclass) {var tmp = function() {};tmp.prototype = superclass.prototype;this.prototype = new tmp();this.prototype.constructor = this;this.prototype.$super = tmp.prototype;};

if(typeof(H8) == 'undefined') H8 = {};
if(typeof(H8.CLI) == 'undefined') H8.CLI = {};

H8.CLI.IndexScript = function() {
};

H8.CLI.IndexScript.OnReady = function() {
	console.log("OnReady()");
	new H8.CLI.IndexScript().$ctor();
};

H8.CLI.IndexScript.NextId = function() {
	H8.CLI.IndexScript.counter = H8.CLI.IndexScript.counter + 1;
	return H8.CLI.IndexScript.counter;
};

H8.CLI.IndexScript.prototype.OnDblClick = function(e /*Ext.EventObject*/) {
	console.log("DblClick");
	console.log(e);
	console.log(this);
};

H8.CLI.IndexScript.prototype.$ctor = function() {
	this.id = H8.CLI.IndexScript.NextId();
	console.log("IndexScript()");
	var loc14 = [];
	var loc5 = {};
	loc5.name = "id";
	loc5.type = "int";
	loc14[0] = loc5;
	var loc6 = {};
	loc6.name = "value";
	loc14[1] = loc6;
	var loc0 = Ext.data.Record.create(loc14);
	var loc7 = {};
	loc7.id = "id";
	var loc1 = new Ext.data.JsonReader(loc7, loc0);
	console.log(loc1);
	var loc8 = {};
	loc8.reader = loc1;
	var loc2 = new Ext.data.Store(loc8);
	var loc15 = [];
	var loc9 = {};
	loc9.id = 1;
	loc9.value = "first";
	loc15[0] = loc9;
	var loc10 = {};
	loc10.id = 2;
	loc10.value = "second";
	loc15[1] = loc10;
	var loc3 = loc15;
	console.log(loc3);
	loc2.loadData(loc3);
	var loc16 = [];
	var loc11 = {};
	loc11.dataIndex = "id";
	loc11.header = "ID";
	loc16[0] = loc11;
	var loc12 = {};
	loc12.dataIndex = "value";
	loc12.header = "Value";
	loc16[1] = loc12;
	var loc4 = loc16;
	var loc13 = {};
	loc13.height = 150;
	loc13.renderTo = "grid";
	loc13.colModel = new Ext.grid.ColumnModel(loc4);
	loc13.store = loc2;
	this.grid = new Ext.grid.GridPanel(loc13);
	console.log(this.grid);
	this.grid.on("dblclick", this.OnDblClick, this);
	return this;
};


console.log("Main()");
Ext.ExtClass.onReady(H8.CLI.IndexScript.OnReady);
