//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Translator.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Translator.Test.Resources.CommonMethods", typeof(CommonMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.prototype._Substring$1 = function(startIndex, length) {
        ///	var CS$4$0001 = length &gt;= 0;
        ///	if (!CS$4$0001) {
        ///		throw new System.ArgumentOutOfRangeException().$ctor$3(&quot;length&quot;, &quot;Cannot be negative.&quot;);
        ///	}
        ///	CS$4$0001 = startIndex &gt;= 0;
        ///	if (!CS$4$0001) {
        ///		throw new System.ArgumentOutOfRangeException().$ctor$3(&quot;startIndex&quot;, &quot;Cannot be negative.&quot;);
        ///	}
        ///	CS$4$0001 = startIndex &lt;= this.length;
        ///	if (!CS$4$0001) {
        ///		throw new System.ArgumentOutOfRangeException().$ctor$3(&quot;startIndex&quot;, &quot;Cannot exceed len [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String__Substring_1 {
            get {
                return ResourceManager.GetString("String__Substring_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.format$0 = function(format, arg0) {
        ///	var CS$0$0001 = $Array(1, null);
        ///	CS$0$0001[0] = arg0;
        ///	var sb = String.formatHelper(null, format, CS$0$0001);
        ///	return sb.toString();
        ///};
        ///.
        /// </summary>
        internal static string String_format_0 {
            get {
                return ResourceManager.GetString("String_format_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.formatHelper = function(result, format, args) {
        ///	var CS$4$0001 = format != null;
        ///	if (!CS$4$0001) {
        ///		throw new System.ArgumentNullException().$ctor$1(&quot;format&quot;);
        ///	}
        ///	CS$4$0001 = args != null;
        ///	if (!CS$4$0001) {
        ///		throw new System.ArgumentNullException().$ctor$1(&quot;args&quot;);
        ///	}
        ///	CS$4$0001 = result != null;
        ///	if (!CS$4$0001) {
        ///		result = new System.Text.StringBuilder().$ctor();
        ///	}
        ///	var ptr = 0;
        ///	var start = ptr;
        ///	while (true) {
        ///		CS$4$0001 = ptr &lt; format.length;
        ///		if (!CS$4$0001) {
        ///			brea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String_formatHelper {
            get {
                return ResourceManager.GetString("String_formatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentException.prototype.$ctor$1 = function(message) {
        ///	System.SystemException.prototype.$ctor$1(this, message);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentException__ctor_1 {
            get {
                return ResourceManager.GetString("System_ArgumentException__ctor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentException.prototype.$ctor$3 = function(message, paramName) {
        ///	System.SystemException.prototype.$ctor$1.call(this, message);
        ///	this.set_ParamName(paramName);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentException__ctor_3 {
            get {
                return ResourceManager.GetString("System_ArgumentException__ctor_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentException.prototype.get_Message = function() {
        ///	var message = System.SystemException.prototype.get_Message.call(this);
        ///	if (this.get_ParamName()) {
        ///		var R_1 = this.get_ParamName().length == 0;
        ///	}
        ///	else {
        ///		R_1 = 1;
        ///	}
        ///	var CS$4$0001 = R_1;
        ///	if (!CS$4$0001) {
        ///		return message + &quot;\nParameter name: &quot; + this.get_ParamName();
        ///	}
        ///	return message;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentException_get_Message {
            get {
                return ResourceManager.GetString("System_ArgumentException_get_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(System.ArgumentException, &apos;System&apos;, &apos;ArgumentNullException&apos;);
        ///
        ///(function() {
        ///	System.ArgumentNullException.DefaultMessage = &quot;Value cannot be null.&quot;;
        ///})();
        ///
        ///System.ArgumentNullException.prototype.$ctor$1 = function(paramName) {
        ///	System.ArgumentException.prototype.$ctor$3.call(this, System.ArgumentNullException.DefaultMessage, paramName);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentNullException {
            get {
                return ResourceManager.GetString("System_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentOutOfRangeException.prototype.$ctor$0 = function() {
        ///	System.ArgumentException.prototype.$ctor$1.call(this, System.ArgumentOutOfRangeException.RangeMessage);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentOutOfRangeException__ctor_0 {
            get {
                return ResourceManager.GetString("System_ArgumentOutOfRangeException__ctor_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentOutOfRangeException.prototype.$ctor$1 = function(paramName) {
        ///	System.ArgumentException.prototype.$ctor$3.call(this, System.ArgumentOutOfRangeException.RangeMessage, paramName);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentOutOfRangeException__ctor_1 {
            get {
                return ResourceManager.GetString("System_ArgumentOutOfRangeException__ctor_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentOutOfRangeException.prototype.$ctor$3 = function(paramName, message) {
        ///	System.ArgumentException.prototype.$ctor$3(this, message, paramName);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentOutOfRangeException__ctor_3 {
            get {
                return ResourceManager.GetString("System_ArgumentOutOfRangeException__ctor_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentOutOfRangeException.prototype.get_Message = function() {
        ///	var message = System.ArgumentException.prototype.get_Message.call(this);
        ///	var CS$4$0001 = this.get_ActualValue() != null;
        ///	if (!CS$4$0001) {
        ///		return message;
        ///	}
        ///	var str2 = &quot;Actual value was &quot; + this.get_ActualValue().toString();
        ///	CS$4$0001 = message != null;
        ///	if (!CS$4$0001) {
        ///		return str2;
        ///	}
        ///	return message + &quot;\n&quot; + str2;
        ///};
        ///.
        /// </summary>
        internal static string System_ArgumentOutOfRangeException_get_Message {
            get {
                return ResourceManager.GetString("System_ArgumentOutOfRangeException_get_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System.Collections.Generic&apos;, &apos;Dictionary$2&apos;, { table: null, linkSlots: null, keySlots: null, valueSlots: null, touchedSlots: 0, emptySlot: 0, count: 0, threshold: 0, hcp: null, generation: 0 });
        ///
        ///(function() {
        ///	System.Collections.Generic.Dictionary$2.INITIAL_SIZE = 10;
        ///	System.Collections.Generic.Dictionary$2.DEFAULT_LOAD_FACTOR = 0.9;
        ///	System.Collections.Generic.Dictionary$2.NO_SLOT = -1;
        ///	System.Collections.Generic.Dictionary$2.HASH_FLAG = -2147483648;
        ///	var D_0 = [11, 19, 37, 73, 109, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Collections_Generic_Dictionary_2 {
            get {
                return ResourceManager.GetString("System_Collections_Generic_Dictionary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.Dictionary$2.prototype.Init = function(capacity, hcp) {
        ///	var CS$4$0000 = capacity &gt;= 0;
        ///	if (!CS$4$0000) {
        ///		throw new System.ArgumentOutOfRangeException().$ctor$1(&quot;capacity&quot;);
        ///	}
        ///	var R_1 = this;
        ///	if (!hcp) {
        ///		var R_2 = System.Collections.Generic.EqualityComparer$1.get_Default();
        ///	}
        ///	else {
        ///		R_2 = hcp;
        ///	}
        ///	R_1.hcp = R_2;
        ///	CS$4$0000 = capacity != 0;
        ///	if (!CS$4$0000) {
        ///		capacity = 10;
        ///	}
        ///	capacity = Math.floor(capacity / 0.9) + 1;
        ///	this.InitArrays(capacity);
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Collections_Generic_Dictionary_2_Init {
            get {
                return ResourceManager.GetString("System_Collections_Generic_Dictionary_2_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.Dictionary$2.prototype.InitArrays = function(size) {
        ///	this.table = $Array(size, 0);
        ///	this.linkSlots = $Array(size, null);
        ///	this.emptySlot = -1;
        ///	this.keySlots = $Array(size, null);
        ///	this.valueSlots = $Array(size, null);
        ///	this.touchedSlots = 0;
        ///	this.threshold = Math.floor(this.table.length * 0.9);
        ///	if (!this.threshold) {
        ///		var R_1 = this.table.length &lt;= 0;
        ///	}
        ///	else {
        ///		R_1 = 1;
        ///	}
        ///	var CS$4$0000 = R_1;
        ///	if (!CS$4$0000) {
        ///		this.threshold = 1;
        ///	}
        ///};
        ///.
        /// </summary>
        internal static string System_Collections_Generic_Dictionary_2_InitArrays {
            get {
                return ResourceManager.GetString("System_Collections_Generic_Dictionary_2_InitArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Console.WriteLine$0 = function(value) {
        ///	System.Console.WriteLine$1(value.toString());
        ///};
        ///.
        /// </summary>
        internal static string System_Console_WriteLine_0 {
            get {
                return ResourceManager.GetString("System_Console_WriteLine_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Console.WriteLine$1 = function(value) {
        ///	console.log(value);
        ///};
        ///.
        /// </summary>
        internal static string System_Console_WriteLine_1 {
            get {
                return ResourceManager.GetString("System_Console_WriteLine_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System&apos;, &apos;Exception&apos;, { message: null, _InnerException_k__BackingField: null, _Source_k__BackingField: null, _StackTrace_k__BackingField: null });
        ///
        ///System.Exception.prototype.set_Message = function(value) {
        ///	this.message = value;
        ///};
        ///
        ///System.Exception.prototype.$ctor$1 = function(message) {
        ///	this.set_Message(message);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_Exception {
            get {
                return ResourceManager.GetString("System_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Exception.prototype.get_Message = function() {
        ///	var CS$4$0001 = this.message != null;
        ///	if (!CS$4$0001) {
        ///		this.message = String.format$0(&quot;Exception of type &apos;{0}&apos; was thrown.&quot;, this.$typename);
        ///	}
        ///	return this.message;
        ///};
        ///.
        /// </summary>
        internal static string System_Exception_get_Message {
            get {
                return ResourceManager.GetString("System_Exception_get_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Exception.prototype.toString = function() {
        ///	var result = new System.Text.StringBuilder().$ctor();
        ///	result.Append$0(this.$typename);
        ///	result.Append$0(&quot;: &quot;).Append$0(this.get_Message());
        ///	var CS$4$0001 = this.get_InnerException() == null;
        ///	if (!CS$4$0001) {
        ///		result.Append$0(&quot; ---&gt; &quot;).Append$0(this.get_InnerException().toString());
        ///		result.AppendLine$0();
        ///		result.Append$0(&quot;  --- End of inner exception stack trace ---&quot;);
        ///	}
        ///	return result.toString();
        ///};
        ///.
        /// </summary>
        internal static string System_Exception_toString {
            get {
                return ResourceManager.GetString("System_Exception_toString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(System.SystemException, &apos;System&apos;, &apos;FormatException&apos;);
        ///
        ///System.FormatException.prototype.$ctor$1 = function(message) {
        ///	System.SystemException.prototype.$ctor$1.call(this, message);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_FormatException {
            get {
                return ResourceManager.GetString("System_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(System.SystemException, &apos;System&apos;, &apos;IndexOutOfRangeException&apos;);
        ///
        ///System.IndexOutOfRangeException.prototype.$ctor$0 = function() {
        ///	System.SystemException.prototype.$ctor$1.call(this, &quot;Array index is out of range.&quot;);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_IndexOutOfRangeException {
            get {
                return ResourceManager.GetString("System_IndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String_FormatSpecifier.prototype.IsWhiteSpace = function() {
        ///	var ch = this.str.charCodeAt(this.ptr);
        ///	if ((((ch &lt; 9) || (ch &gt; 13)) &amp;&amp; (ch != 32)) &amp;&amp; (ch != 133)) {
        ///		var R_1 = ch == 8287;
        ///	}
        ///	else {
        ///		R_1 = 1;
        ///	}
        ///	return R_1;
        ///};
        ///.
        /// </summary>
        internal static string System_String_FormatSpecifier_IsWhiteSpace {
            get {
                return ResourceManager.GetString("System_String_FormatSpecifier_IsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String_FormatSpecifier.prototype.ParseDecimal = function() {
        ///	var p = this.ptr;
        ///	var n = 0;
        ///	while (true) {
        ///		var CS$4$0001 = true;
        ///		var ch = this.str.charCodeAt(p);
        ///		if (ch &gt;= 48) {
        ///			var R_1 = 57 &gt;= ch;
        ///		}
        ///		else {
        ///			R_1 = 0;
        ///		}
        ///		CS$4$0001 = R_1;
        ///		if (!CS$4$0001) {
        ///			break;
        ///		}
        ///		n = ((n * 10) + ch) - 48;
        ///		p = p + 1;
        ///	}
        ///	CS$4$0001 = p != this.ptr;
        ///	if (!CS$4$0001) {
        ///		return -1;
        ///	}
        ///	this.ptr = p;
        ///	return n;
        ///};
        ///.
        /// </summary>
        internal static string System_String_FormatSpecifier_ParseDecimal {
            get {
                return ResourceManager.GetString("System_String_FormatSpecifier_ParseDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String_FormatSpecifier.prototype.ParseFormatSpecifier = function() {
        ///	try {
        ///		this.n = this.ParseDecimal();
        ///		var CS$4$0000 = this.n &gt;= 0;
        ///		if (!CS$4$0000) {
        ///			throw new System.FormatException().$ctor$1(&quot;Invalid argument specifier.&quot;);
        ///		}
        ///		CS$4$0000 = this.str.charAt(this.ptr) != &apos;,&apos;;
        ///		if (!CS$4$0000) {
        ///			this.ptr = this.ptr + 1;
        ///			while (true) {
        ///				CS$4$0000 = this.IsWhiteSpace();
        ///				if (!CS$4$0000) {
        ///					break;
        ///				}
        ///				this.ptr = this.ptr + 1;
        ///			}
        ///			var start = this.pt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_String_FormatSpecifier_ParseFormatSpecifier {
            get {
                return ResourceManager.GetString("System_String_FormatSpecifier_ParseFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(System.Exception, &apos;System&apos;, &apos;SystemException&apos;);
        ///
        ///System.SystemException.prototype.$ctor$1 = function(message) {
        ///	System.Exception.prototype.$ctor$1.call(this, message);
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_SystemException {
            get {
                return ResourceManager.GetString("System_SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.$ctor = function() {
        ///	this.value = &quot;&quot;;
        ///	return this;
        ///};
        ///.
        /// </summary>
        internal static string System_Text_StringBuilder__ctor {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder__ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.Append$0 = function(value) {
        ///	var CS$4$0001 = value != null;
        ///	if (!CS$4$0001) {
        ///		return this;
        ///	}
        ///	CS$4$0001 = value.length != 0;
        ///	if (!CS$4$0001) {
        ///		this.value = value;
        ///		return this;
        ///	}
        ///	this.value = this.value + value;
        ///	return this;
        ///};.
        /// </summary>
        internal static string System_Text_StringBuilder_Append_0 {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder_Append_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.Append$1 = function(value) {
        ///	return this.Append$0(value.toString());
        ///};
        ///.
        /// </summary>
        internal static string System_Text_StringBuilder_Append_1 {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder_Append_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.Append$3 = function(value, repeatCount) {
        ///	var i = 0;
        ///	while (true) {
        ///		var CS$4$0001 = i &lt; repeatCount;
        ///		if (!CS$4$0001) {
        ///			break;
        ///		}
        ///		this.Append$1(value);
        ///		i = i + 1;
        ///	}
        ///	return this;
        ///};.
        /// </summary>
        internal static string System_Text_StringBuilder_Append_3 {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder_Append_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.Append$5 = function(value, startIndex, count) {
        ///	var CS$4$0001 = value != null;
        ///	if (!CS$4$0001) {
        ///		if (startIndex) {
        ///			var R_1 = count == 0;
        ///		}
        ///		else {
        ///			R_1 = 1;
        ///		}
        ///		CS$4$0001 = R_1;
        ///		if (!CS$4$0001) {
        ///			throw new System.ArgumentNullException().$ctor$1(&quot;value&quot;);
        ///		}
        ///		return this;
        ///	}
        ///	if ((count &gt;= 0) &amp;&amp; (startIndex &gt;= 0)) {
        ///		R_1 = startIndex &lt;= (value.length - count);
        ///	}
        ///	else {
        ///		R_1 = 0;
        ///	}
        ///	CS$4$0001 = R_1;
        ///	if (!CS$4$0001) {
        ///		throw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Text_StringBuilder_Append_5 {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder_Append_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.StringBuilder.prototype.toString = function() {
        ///	return this.value;
        ///};
        ///.
        /// </summary>
        internal static string System_Text_StringBuilder_toString {
            get {
                return ResourceManager.GetString("System_Text_StringBuilder_toString", resourceCulture);
            }
        }
    }
}
