//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Translator.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Translator.Test.Resources.SystemTestData", typeof(SystemTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests_Impl&apos;);
        ///
        ///H8.SystemTests_Impl.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Impl.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Impl.prototype.CallFoo = function() {
        ///	this.Foo();
        ///};
        ///
        ///$Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.CallThisInterfaceMethod = function() {
        ///	var x = new H8.SystemTests_Impl().$ctor();
        ///	x.CallFoo();
        ///};
        ///.
        /// </summary>
        internal static string CallThisInterfaceMethod {
            get {
                return ResourceManager.GetString("CallThisInterfaceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.box_OnMouseOver = function(evt) {
        ///};
        ///
        ///H8.SystemTests.prototype.CastInterface = function() {
        ///	var element = $doc.getElementById(&quot;box&quot;);
        ///	var box = element;
        ///	box.onmouseover = $Delegate(this, this.box_OnMouseOver);
        ///};
        ///.
        /// </summary>
        internal static string CastInterface {
            get {
                return ResourceManager.GetString("CastInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2009, Frank Laub
        /////
        ///// This file is part of DotWeb.
        /////
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        /////
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests_Base&apos;);
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///$Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.TestBase = function() {
        ///	var x = new H8.SystemTests_Base().$ctor();
        ///	x.Foo();
        ///};
        ///.
        /// </summary>
        internal static string TestBase {
            get {
                return ResourceManager.GetString("TestBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests_Base&apos;);
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///$Class(H8.SystemTests_Base, &apos;H8&apos;, &apos;SystemTests_Derived&apos;);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor();
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo();
        ///};
        ///
        ///$Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.TestDerived = function( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDerived {
            get {
                return ResourceManager.GetString("TestDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests_Base&apos;);
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///$Class(H8.SystemTests_Base, &apos;H8&apos;, &apos;SystemTests_Derived&apos;);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor();
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo();
        ///};
        ///
        ///$Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.TestDerivedThruBase = f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDerivedThruBase {
            get {
                return ResourceManager.GetString("TestDerivedThruBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;H8&apos;, &apos;SystemTests_Base&apos;);
        ///
        ///H8.SystemTests_Base.prototype.$ctor = function() {
        ///	return this;
        ///};
        ///
        ///$Class(H8.SystemTests_Base, &apos;H8&apos;, &apos;SystemTests_Derived&apos;);
        ///
        ///H8.SystemTests_Derived.prototype.$ctor = function() {
        ///	this.$super.$ctor();
        ///	return this;
        ///};
        ///
        ///H8.SystemTests_Base.prototype.Foo = function() {
        ///};
        ///
        ///H8.SystemTests_Derived.prototype.Foo = function() {
        ///	this.$super.Foo();
        ///	this.Foo();
        ///};
        ///
        ///$Class(null, &apos;H8&apos;, &apos;SystemTests&apos;);
        ///
        ///H8.SystemTests.prototype.UseBase = function(x) { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDerivedThruBaseIndirect {
            get {
                return ResourceManager.GetString("TestDerivedThruBaseIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System.Collections.Generic&apos;, &apos;List$1&apos;);
        ///
        ///System.Collections.Generic.List$1.prototype.$ctor$0 = function() {
        ///	this.items = new Array();
        ///	return this;
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.Add$0 = function(item) {
        ///	this.items.push(item);
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.IndexOf$0 = function(item) {
        ///	var V_0 = this.items.indexOf(item);
        ///	return V_0;
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.toString = function() {
        ///	var V_0 = &quot;[ &quot; + this.items.toStrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestGenericMethod {
            get {
                return ResourceManager.GetString("TestGenericMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.SystemTests.prototype.TestJsArray = function() {
        ///	var array = new Array();
        ///	if (Array.isArray(array)) {
        ///		var part = array.slice(0, 1);
        ///		System.Console.WriteLine$1(part.join(&quot;,&quot;));
        ///	}
        ///	array.splice(0, 0);
        ///	array.splice(0, 0, 1);
        ///	array.splice(0, 0, 1, &quot;two&quot;);
        ///	var x = new Array(1, 2);
        ///	System.Console.WriteLine$0(x[0]);
        ///	x[1] = 1;
        ///};
        ///.
        /// </summary>
        internal static string TestJsArray {
            get {
                return ResourceManager.GetString("TestJsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System.Collections.Generic&apos;, &apos;List$1&apos;);
        ///
        ///System.Collections.Generic.List$1.prototype.$ctor$0 = function() {
        ///	this.items = new Array();
        ///	return this;
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.Add$0 = function(item) {
        ///	this.items.push(item);
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.toString = function() {
        ///	var V_0 = &quot;[ &quot; + this.items.toString() + &quot; ]&quot;;
        ///	return V_0;
        ///};
        ///
        ///$Class(null, &apos;System&apos;, &apos;Console&apos;);
        ///
        ///System.Console.WriteLine$1 = function(value) {
        ///	console.log( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestList {
            get {
                return ResourceManager.GetString("TestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System.Collections.Generic&apos;, &apos;List$1&apos;);
        ///
        ///System.Collections.Generic.List$1.prototype.$ctor$0 = function() {
        ///	this.items = new Array();
        ///	return this;
        ///};
        ///
        ///$Class(null, &apos;System.Collections.Generic&apos;, &apos;List$1_Enumerator&apos;);
        ///
        ///System.Collections.Generic.List$1_Enumerator.prototype.$ctor = function(list) {
        ///	this.list = list;
        ///	this.index = 0;
        ///	this.current = null;
        ///	return this;
        ///};
        ///
        ///System.Collections.Generic.List$1.prototype.GetEnumerator = function() {
        ///	var V_0 = new System.Collections [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestListEnumerator {
            get {
                return ResourceManager.GetString("TestListEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Class(null, &apos;System&apos;, &apos;Console&apos;);
        ///
        ///System.Console.WriteLine$0 = function(value) {
        ///	console.log(value);
        ///};
        ///
        ///$Class(null, &apos;System&apos;, &apos;Exception&apos;);
        ///
        ///$Class(System.Exception, &apos;System&apos;, &apos;SystemException&apos;);
        ///
        ///$Class(System.SystemException, &apos;System&apos;, &apos;ArgumentException&apos;);
        ///
        ///$Class(System.ArgumentException, &apos;System&apos;, &apos;ArgumentOutOfRangeException&apos;);
        ///
        ///System.ArgumentOutOfRangeException.get_RangeMessage = function() {
        ///	var V_0 = &quot;Specified argument was out of the range of valid values.&quot;;
        ///	return V_0;
        ///}; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
    }
}
