//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Javascript.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Javascript.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Source
        ///{
        ///	public class Conditions
        ///	{
        ///		public void SimpleIf(int x) {
        ///			if (x == 12) {
        ///				x = 14;
        ///			}
        ///		}
        ///
        ///		public void SimpleIfElse(int x) {
        ///			if (x == 12) {
        ///				x = 42;
        ///			}
        ///			else {
        ///				x = 128;
        ///			}
        ///			Console.WriteLine(1);
        ///		}
        ///
        ///		public void SimpleIfOr(int a) {
        ///			if (a == 12 || a == 14) {
        ///				a = 42;
        ///			}
        ///		}
        ///
        ///		public void SimpleIfAnd(int a) {
        ///			if (a &lt; 12 &amp;&amp; a &gt; 2) {
        ///				a = 42;
        ///			}
        ///		}
        ///
        ///		public string NullCoalesce(string s) {
        ///			re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIf = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 14;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_NullCoalesce {
            get {
                return ResourceManager.GetString("Conditions_NullCoalesce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIf = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 14;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_ReturnNestedTernary {
            get {
                return ResourceManager.GetString("Conditions_ReturnNestedTernary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIf = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 14;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_ReturnTernary {
            get {
                return ResourceManager.GetString("Conditions_ReturnTernary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIf = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 14;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SimpleIf {
            get {
                return ResourceManager.GetString("Conditions_SimpleIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIf = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 14;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SimpleIf1 {
            get {
                return ResourceManager.GetString("Conditions_SimpleIf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIfAnd = function(/*System.Int32*/ a) {
        ///	if ((a &lt; 12) &amp;&amp; (a &gt; 2)) {
        ///		a = 42;
        ///	}        ///}
        ///.
        /// </summary>
        internal static string Conditions_SimpleIfAnd {
            get {
                return ResourceManager.GetString("Conditions_SimpleIfAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIfElse = function(/*System.Int32*/ x) {
        ///	if(x == 12) {
        ///		x = 42;
        ///	}
        ///	else {
        ///		x = 128;
        ///	}
        ///	System.Console.WriteLine(1);
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SimpleIfElse {
            get {
                return ResourceManager.GetString("Conditions_SimpleIfElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SimpleIfOr = function(/*System.Int32*/ a) {
        ///	if((a == 12) || (a == 14)) {
        ///		a = 42;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SimpleIfOr {
            get {
                return ResourceManager.GetString("Conditions_SimpleIfOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SingleAnd = function(/*System.Int32*/ x, /*System.Int32*/ y) {
        ///	return ((x == 1) &amp;&amp; (y == 2));
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SingleAnd {
            get {
                return ResourceManager.GetString("Conditions_SingleAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.Conditions.prototype.SingleAnd = function(/*System.Int32*/ x, /*System.Int32*/ y) {
        ///	return ((x == 1) || (y == 2));
        ///}
        ///.
        /// </summary>
        internal static string Conditions_SingleOr {
            get {
                return ResourceManager.GetString("Conditions_SingleOr", resourceCulture);
            }
        }
    }
}
