//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Translator.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphBuilderTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphBuilderTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Translator.Test.GraphBuilderTestData", typeof(GraphBuilderTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0000: ret Return
        ///	0000: ret Return.
        /// </summary>
        internal static string NullBlock {
            get {
                return ResourceManager.GetString("NullBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0010: ret Return
        ///	0000: ldstr &quot;hello&quot; Next
        ///	0005: call [return: System.Void] System.Console::WriteLine() Call
        ///	0010: ret Return.
        /// </summary>
        internal static string OneBlock {
            get {
                return ResourceManager.GetString("OneBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0001: brfalse.s 0013 Cond_Branch
        ///	Out: B2, B3
        ///	0000: ldarg.1 Next
        ///	0001: brfalse.s 0013 Cond_Branch
        ///
        ///B2: 0003 - 0008: call [return: System.Void] System.Console::WriteLine() Call
        ///	In : B1
        ///	Out: B3
        ///	0003: ldstr &quot;x&quot; Next
        ///	0008: call [return: System.Void] System.Console::WriteLine() Call
        ///
        ///B3: 0013 - 0013: ret Return
        ///	In : B1, B2
        ///	0013: ret Return
        ///.
        /// </summary>
        internal static string SimpleIf {
            get {
                return ResourceManager.GetString("SimpleIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright 2010, Frank Laub
        ///// 
        ///// This file is part of DotWeb.
        ///// 
        ///// DotWeb is free software: you can redistribute it and/or modify
        ///// it under the terms of the GNU General Public License as published by
        ///// the Free Software Foundation, either version 3 of the License, or
        ///// (at your option) any later version.
        ///// 
        ///// DotWeb is distributed in the hope that it will be useful,
        ///// but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0013: switch [0032, 0044, 0044] Cond_Branch
        ///	Out: B2, B3, B4
        ///	0000: ldstr &quot;enter&quot; Next
        ///	0005: call [return: System.Void] System.Console::WriteLine() Call
        ///	0010: ldarg.1 Next
        ///	0011: stloc.0 Next
        ///	0012: ldloc.0 Next
        ///	0013: switch [0032, 0044, 0044] Cond_Branch
        ///
        ///B4: 0044 - 0054: br.s 0066 Branch
        ///	In : B1
        ///	Out: B6
        ///	0044: ldstr &quot;One &amp; Two&quot; Next
        ///	0049: call [return: System.Void] System.Console::WriteLine() Call
        ///	0054: br.s 0066 Branch
        ///
        ///B3: 0032 - 0042: br.s 0066 Branch
        ///	In : B1
        ///	Out:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0001: stloc.0 Next
        ///	Out: B2
        ///	0000: ldc.i4.0 Next
        ///	0001: stloc.0 Next
        ///
        ///B2: 0002 - 0015: bne.un.s 0029 Cond_Branch
        ///	In : B1, B4
        ///	Out: B3, B4
        ///	0002: ldstr &quot;top&quot; Next
        ///	0007: call [return: System.Void] System.Console::WriteLine() Call
        ///	0012: ldloc.0 Next
        ///	0013: ldc.i4.s 10 Next
        ///	0015: bne.un.s 0029 Cond_Branch
        ///
        ///B4: 0029 - 0043: br.s 0002 Branch
        ///	In : B2
        ///	Out: B2
        ///	0029: ldstr &quot;loop&quot; Next
        ///	0034: call [return: System.Void] System.Console::WriteLine() Call
        ///	0039: ldloc.0 Next
        ///	0040: ld [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TryCatchFinally {
            get {
                return ResourceManager.GetString("TryCatchFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0001: stloc.0 Next
        ///	Out: B2
        ///	0000: ldc.i4.0 Next
        ///	0001: stloc.0 Next
        ///
        ///B2: 0002 - 0015: bne.un.s 0029 Cond_Branch
        ///	In : B1, B4
        ///	Out: B3, B4
        ///	0002: ldstr &quot;top&quot; Next
        ///	0007: call [return: System.Void] System.Console::WriteLine() Call
        ///	0012: ldloc.0 Next
        ///	0013: ldc.i4.s 10 Next
        ///	0015: bne.un.s 0029 Cond_Branch
        ///
        ///B4: 0029 - 0043: br.s 0002 Branch
        ///	In : B2
        ///	Out: B2
        ///	0029: ldstr &quot;loop&quot; Next
        ///	0034: call [return: System.Void] System.Console::WriteLine() Call
        ///	0039: ldloc.0 Next
        ///	0040: ld [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhileBreak {
            get {
                return ResourceManager.GetString("WhileBreak", resourceCulture);
            }
        }
    }
}
