//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.Translator.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphBuilderTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphBuilderTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotWeb.Translator.Test.GraphBuilderTestData", typeof(GraphBuilderTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0000: ret Return
        ///	0000: ret Return.
        /// </summary>
        internal static string NullBlock {
            get {
                return ResourceManager.GetString("NullBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0010: ret Return
        ///	0000: ldstr &quot;hello&quot; Next
        ///	0005: call [return: System.Void] System.Console::WriteLine() Call
        ///	0010: ret Return.
        /// </summary>
        internal static string OneBlock {
            get {
                return ResourceManager.GetString("OneBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0001: brfalse.s 0013 Cond_Branch
        ///	Out: B3, B2
        ///	0000: ldarg.1 Next
        ///	0001: brfalse.s 0013 Cond_Branch
        ///
        ///B2: 0003 - 0008: call [return: System.Void] System.Console::WriteLine() Call
        ///	In : B1
        ///	Out: B3
        ///	0003: ldstr &quot;x&quot; Next
        ///	0008: call [return: System.Void] System.Console::WriteLine() Call
        ///
        ///B3: 0013 - 0013: ret Return
        ///	In : B1, B2
        ///	0013: ret Return
        ///.
        /// </summary>
        internal static string SimpleIf {
            get {
                return ResourceManager.GetString("SimpleIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.DotWeb;
        ///using System;
        ///
        ///namespace H8
        ///{
        ///	[JsNamespace]
        ///	class GraphBuilderTest
        ///	{
        ///		public void NullBlock() {
        ///		}
        ///
        ///		public void OneBlock() {
        ///			Console.WriteLine(&quot;hello&quot;);
        ///		}
        ///
        ///		public void SimpleIf(bool x) {
        ///			if (x) {
        ///				Console.WriteLine(&quot;x&quot;);
        ///			}
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1: 0000 - 0001: brfalse.s 0013 Cond_Branch
        ///	Out: B3, B2
        ///	0000: ldarg.1 Next
        ///	0001: brfalse.s 0013 Cond_Branch
        ///
        ///B2: 0003 - 0008: call [return: System.Void] System.Console::WriteLine() Call
        ///	In : B1
        ///	Out: B3
        ///	0003: ldstr &quot;x&quot; Next
        ///	0008: call [return: System.Void] System.Console::WriteLine() Call
        ///
        ///B3: 0013 - 0013: ret Return
        ///	In : B1, B2
        ///	0013: ret Return
        ///.
        /// </summary>
        internal static string WhileBreak {
            get {
                return ResourceManager.GetString("WhileBreak", resourceCulture);
            }
        }
    }
}
